<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC0432J4-T440P" name="chromeTest" tests="1" failures="1" timestamp="12 Apr 2018 04:50:18 GMT" time="105.094" errors="0">
  <testcase name="SubmitDispute_Incentive" time="64.602" classname="DisputeEndtoEndFlow_DisputeTab.SubmitDispute">
    <failure type="java.lang.AssertionError" message="Failed TestCaseSubmitDispute_Incentive">
      <![CDATA[java.lang.AssertionError: Failed TestCaseSubmitDispute_Incentive
	at com.calliduscloud.testing.util.SeleniumMethods.catch_code(SeleniumMethods.java:559)
	at DisputeEndtoEndFlow_DisputeTab.SubmitDispute.SubmitDispute_Incentive(SubmitDispute.java:89)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- SubmitDispute_Incentive -->
</testsuite> <!-- chromeTest -->
