<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC0432J4-T440P" name="com.calliduscloud.testing.communicator.PayeeRespondedtoManagerInquiry$ManagerInquirytoPayee" tests="1" failures="1" timestamp="8 Mar 2018 04:27:51 GMT" time="23.889" errors="0">
  <testcase name="ManagerSentInquiry" time="23.889" classname="com.calliduscloud.testing.communicator.PayeeRespondedtoManagerInquiry$ManagerInquirytoPayee">
    <failure type="java.lang.AssertionError" message="Failed TestCaseManagerSentInquiry">
      <![CDATA[java.lang.AssertionError: Failed TestCaseManagerSentInquiry
	at org.testng.Assert.fail(Assert.java:94)
	at com.calliduscloud.testing.util.SeleniumMethods.catch_code(SeleniumMethods.java:553)
	at com.calliduscloud.testing.communicator.PayeeRespondedtoManagerInquiry$ManagerInquirytoPayee.ManagerSentInquiry(PayeeRespondedtoManagerInquiry.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- ManagerSentInquiry -->
</testsuite> <!-- com.calliduscloud.testing.communicator.PayeeRespondedtoManagerInquiry$ManagerInquirytoPayee -->
